// 
// *  This file was automatically generated by MoMEMta-MaGMEE,
// *  A MadGraph Matrix Element Exporter plugin for MoMEMta.
// *
// *  It is subject to MoMEMta-MaGMEE's license and copyright:
// *
// *  Copyright (C) 2016  Universite catholique de Louvain (UCL), Belgium
// *
// *  This program is free software: you can redistribute it and/or modify
// *  it under the terms of the GNU General Public License as published by
// *  the Free Software Foundation, either version 3 of the License, or
// *  (at your option) any later version.
// *
// *  This program is distributed in the hope that it will be useful,
// *  but WITHOUT ANY WARRANTY; without even the implied warranty of
// *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// *  GNU General Public License for more details.
// *
// *  You should have received a copy of the GNU General Public License
// *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
// 

#pragma once

#include <complex> 
#include <vector> 
#include <utility> 
#include <map> 
#include <functional> 

#include <Parameters_sm.h> 
#include <SubProcess.h> 

#include <momemta/MatrixElement.h> 

namespace DY_ME_sm 
{

//==========================================================================
// A class for calculating the matrix elements for
// Process: g g > a u u~ WEIGHTED<=4 @2
// Process: g g > a c c~ WEIGHTED<=4 @2
// Process: g g > a d d~ WEIGHTED<=4 @2
// Process: g g > a s s~ WEIGHTED<=4 @2
// Process: g u > a g u WEIGHTED<=4 @2
// Process: g c > a g c WEIGHTED<=4 @2
// Process: g d > a g d WEIGHTED<=4 @2
// Process: g s > a g s WEIGHTED<=4 @2
// Process: g u~ > a g u~ WEIGHTED<=4 @2
// Process: g c~ > a g c~ WEIGHTED<=4 @2
// Process: g d~ > a g d~ WEIGHTED<=4 @2
// Process: g s~ > a g s~ WEIGHTED<=4 @2
// Process: u u > a u u WEIGHTED<=4 @2
// Process: c c > a c c WEIGHTED<=4 @2
// Process: u u~ > a g g WEIGHTED<=4 @2
// Process: c c~ > a g g WEIGHTED<=4 @2
// Process: u u~ > a u u~ WEIGHTED<=4 @2
// Process: c c~ > a c c~ WEIGHTED<=4 @2
// Process: d d > a d d WEIGHTED<=4 @2
// Process: s s > a s s WEIGHTED<=4 @2
// Process: d d~ > a g g WEIGHTED<=4 @2
// Process: s s~ > a g g WEIGHTED<=4 @2
// Process: d d~ > a d d~ WEIGHTED<=4 @2
// Process: s s~ > a s s~ WEIGHTED<=4 @2
// Process: u~ u~ > a u~ u~ WEIGHTED<=4 @2
// Process: c~ c~ > a c~ c~ WEIGHTED<=4 @2
// Process: d~ d~ > a d~ d~ WEIGHTED<=4 @2
// Process: s~ s~ > a s~ s~ WEIGHTED<=4 @2
// Process: u c > a u c WEIGHTED<=4 @2
// Process: u d > a u d WEIGHTED<=4 @2
// Process: u s > a u s WEIGHTED<=4 @2
// Process: c d > a c d WEIGHTED<=4 @2
// Process: c s > a c s WEIGHTED<=4 @2
// Process: u u~ > a c c~ WEIGHTED<=4 @2
// Process: c c~ > a u u~ WEIGHTED<=4 @2
// Process: u u~ > a d d~ WEIGHTED<=4 @2
// Process: u u~ > a s s~ WEIGHTED<=4 @2
// Process: c c~ > a d d~ WEIGHTED<=4 @2
// Process: c c~ > a s s~ WEIGHTED<=4 @2
// Process: u c~ > a u c~ WEIGHTED<=4 @2
// Process: c u~ > a c u~ WEIGHTED<=4 @2
// Process: u d~ > a u d~ WEIGHTED<=4 @2
// Process: u s~ > a u s~ WEIGHTED<=4 @2
// Process: c d~ > a c d~ WEIGHTED<=4 @2
// Process: c s~ > a c s~ WEIGHTED<=4 @2
// Process: d s > a d s WEIGHTED<=4 @2
// Process: d u~ > a d u~ WEIGHTED<=4 @2
// Process: d c~ > a d c~ WEIGHTED<=4 @2
// Process: s u~ > a s u~ WEIGHTED<=4 @2
// Process: s c~ > a s c~ WEIGHTED<=4 @2
// Process: d d~ > a u u~ WEIGHTED<=4 @2
// Process: d d~ > a c c~ WEIGHTED<=4 @2
// Process: s s~ > a u u~ WEIGHTED<=4 @2
// Process: s s~ > a c c~ WEIGHTED<=4 @2
// Process: d d~ > a s s~ WEIGHTED<=4 @2
// Process: s s~ > a d d~ WEIGHTED<=4 @2
// Process: d s~ > a d s~ WEIGHTED<=4 @2
// Process: s d~ > a s d~ WEIGHTED<=4 @2
// Process: u~ c~ > a u~ c~ WEIGHTED<=4 @2
// Process: u~ d~ > a u~ d~ WEIGHTED<=4 @2
// Process: u~ s~ > a u~ s~ WEIGHTED<=4 @2
// Process: c~ d~ > a c~ d~ WEIGHTED<=4 @2
// Process: c~ s~ > a c~ s~ WEIGHTED<=4 @2
// Process: d~ s~ > a d~ s~ WEIGHTED<=4 @2
//--------------------------------------------------------------------------

class P2_Sigma_sm_gg_auux: public momemta::MatrixElement 
{
  public:

    // Constructor & destructor
    P2_Sigma_sm_gg_auux(const ParameterSet& configuration); 
    virtual ~P2_Sigma_sm_gg_auux() {}; 

    // Calculate flavour-independent parts of cross section.
    virtual momemta::MatrixElement::Result compute(
    const std::pair < std::vector<double> , std::vector<double> >
        &initialMomenta,
    const std::vector < std::pair < int, std::vector<double> > > &finalState); 

    virtual std::shared_ptr < momemta::MEParameters > getParameters() 
    {
      return params; 
    }

    // Make sure all helicity combinations are tried again (forget optimisation
    // consisting of not evaluating helicities which have given a zero result
    // once)
    virtual void resetHelicities(); 

  private:

    // default constructor should be hidden
    P2_Sigma_sm_gg_auux() = delete; 

    // list of helicities combinations
    const int helicities[32][5] = {{-1, -1, -1, -1, -1}, {-1, -1, -1, -1, 1},
        {-1, -1, -1, 1, -1}, {-1, -1, -1, 1, 1}, {-1, -1, 1, -1, -1}, {-1, -1,
        1, -1, 1}, {-1, -1, 1, 1, -1}, {-1, -1, 1, 1, 1}, {-1, 1, -1, -1, -1},
        {-1, 1, -1, -1, 1}, {-1, 1, -1, 1, -1}, {-1, 1, -1, 1, 1}, {-1, 1, 1,
        -1, -1}, {-1, 1, 1, -1, 1}, {-1, 1, 1, 1, -1}, {-1, 1, 1, 1, 1}, {1,
        -1, -1, -1, -1}, {1, -1, -1, -1, 1}, {1, -1, -1, 1, -1}, {1, -1, -1, 1,
        1}, {1, -1, 1, -1, -1}, {1, -1, 1, -1, 1}, {1, -1, 1, 1, -1}, {1, -1,
        1, 1, 1}, {1, 1, -1, -1, -1}, {1, 1, -1, -1, 1}, {1, 1, -1, 1, -1}, {1,
        1, -1, 1, 1}, {1, 1, 1, -1, -1}, {1, 1, 1, -1, 1}, {1, 1, 1, 1, -1},
        {1, 1, 1, 1, 1}};

    // Private functions to calculate the matrix element for all subprocesses
    // Wavefunctions
    void calculate_wavefunctions(const int perm[], const int hel[]); 
    std::complex<double> amp[168]; 

    // Matrix elements
    double matrix_2_gg_auux(); 
    double matrix_2_gg_addx(); 
    double matrix_2_gu_agu(); 
    double matrix_2_gd_agd(); 
    double matrix_2_gux_agux(); 
    double matrix_2_gdx_agdx(); 
    double matrix_2_uu_auu(); 
    double matrix_2_uux_agg(); 
    double matrix_2_uux_auux(); 
    double matrix_2_dd_add(); 
    double matrix_2_ddx_agg(); 
    double matrix_2_ddx_addx(); 
    double matrix_2_uxux_auxux(); 
    double matrix_2_dxdx_adxdx(); 
    double matrix_2_uc_auc(); 
    double matrix_2_ud_aud(); 
    double matrix_2_uux_accx(); 
    double matrix_2_uux_addx(); 
    double matrix_2_ucx_aucx(); 
    double matrix_2_udx_audx(); 
    double matrix_2_ds_ads(); 
    double matrix_2_dux_adux(); 
    double matrix_2_ddx_auux(); 
    double matrix_2_ddx_assx(); 
    double matrix_2_dsx_adsx(); 
    double matrix_2_uxcx_auxcx(); 
    double matrix_2_uxdx_auxdx(); 
    double matrix_2_dxsx_adxsx(); 

    // map of final states
    std::map < std::vector<int> , std::vector < SubProcess <
        P2_Sigma_sm_gg_auux >> > mapFinalStates;

    // Reference to the model parameters instance passed in the constructor
    std::shared_ptr < Parameters_sm > params; 

    // vector with external particle masses
    std::vector < std::reference_wrapper<double> > mME; 

    // vector with momenta (to be changed each event)
    double * momenta[5]; 
}; 


}

